spring:
  application:
    name: config-server
  cloud:
    bus:
      env:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/fu-ry17/demo-config

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888
